### ISSUE TITLE
AttriCLIP Code

### ISSUE THREAD

**Issue by MoringLotus** [sun-hailong/Awesome-Incremental-Learning-with-Pre-trained-Models#4]
Thanks for your collection of Incremental learning paper, recently I notice a paper AttriCLIP: A Non-Incremental Learner for Incremental Knowledge Learning (CVPR23) which also in your repo, do you have any idea to find the code？

**Comment by sun-hailong** [comment]
Thank you for your interest in this repo! Since I can not access the AttriCLIP code provided by the official URL, I suggest that you email the author for the codes.
